### PR TITLE
Fixed warnings

### PR DESCRIPTION
**Pull request by Stevenah**
Fixed warnings related to 'createEl' and 'plugin'.

### CODE REVIEW

**Comment by vhmth** [comment]
This looks great. @spchuang can we get this landed? Using `.plugin` instead of `.registerPlugin` results in the following warnings in production for us:

screen shot 2017-09-20 at 10 45 39 pm

**Comment by vhmth** [comment]
@spchuang if you are no longer maintaining this repo, would you like me to fork into the main [Loom](https://github.com/loomhq) org? I feel this repo may be healthier if you either allow us to be the main markers repo or if (ideally) you make myself and one other Loom member (@paulius005 perhaps?) co-owners/collaborators of the repo so we have the autonomy to look at PRs and close them more quickly. I'd opt for the latter rather than us cloning into the Loom org and being the main repo since then other peeps who have this as an entry in their `package.json` wouldn't have to make any changes.

**Comment by spchuang** [comment]
That's a good plan. I will add both of you as repo collaborators so it'll be easier for you guys to close PR.

**Comment by vhmth** [comment]
Sweet! Thanks @spchuang.

**Comment by paulius005** [comment]
Thanks @spchuang!

**Comment by vhmth** [comment]
@spchuang it seems you use a combo of git tags and updating the README to create a changelog entry for a bump in version. How would you like me to open a PR/what's your publish flow? I'd like to bump the version for this change and update in the main Loom repo.

**Pull request merged**
